#%RAML 1.0
title: pluskimble
description: pluskimble Api
version: 0.0
baseUri: http://localhost:8081/pluskimble/v0

uses:
  resource:  types/resource.raml
  kimble_status: types/kimble_status.raml
  proyect_resource: types/proyect_resource.raml
  attemp: types/attemp.raml
  resource_status: types/resource_status.raml
  resource_project_hours: types/resource_project_hours.raml
  pagination: glapi-global-apis-commons-commons/types/pagination.raml

resourceTypes: 
  collection: !include glapi-global-apis-commons-commons/resourceTypes/collection.raml

traits: 
  pageable: !include glapi-global-apis-commons-commons/traits/pageable.raml

/resource:
  description: |
    resource list
  type: collection
  get:
    is: [pageable]
    description: |
      resource lists
    queryParameters:
      resource.id:
        description: |
          resource id
        type: number
        required: false
        example: 1
      resource.name:
        description: |
          resource name
        type: string
        required: false
        example: "ANTONIO"
      resource.last_name:
        description: |
          resource last name
        type: string
        required: false
        example: "ANZURES"
      resource.second_last_name:
        description: |
          resource second last name
        type: string
        required: false
        example: "MONTECILLO"
      resource.fkResourceStatus:
        description: |
          resource status
        type: number
        required: true
        example: 1
      resource.letters_gft:
        description: |
          resource letter identifier
        type: string
        required: false
        example: "JOAZ"
      resource.starting_date:
        description: |
          resource date incomming work
        type: string
        required: false
        example: "2019-10-10"
      resource.end_date:
        description: |
          resource date work out
        type: string
        required: false
        example: "2023-10-10"
      resource.comentary:
        description: |
          identify the text referring to a resource
        type: string
        required: false
        example: "PRUEBA DE COMENTARIO"

    responses:
      200:
        body:
          application/json:
            type: resources
            example: !include examples/resources/get_200.json

  post:
    body:
      application/json:
        properties:
      resource.name:
        type: string
        required: false
        example: "ANTONIO"
      resource.last_name:
        type: string
        required: false
        example: "ANZURES"
      resource.second_last_name:
        type: string
        required: false
        example: "MONTECILLO"
      resource.fkResourceStatus:
        type: number
        required: true
        example: 1
      resource.letters_gft:
        type: string
        required: false
        example: "JOAZ"
      resource.starting_date:
        type: string
        required: false
        example: "2019-10-10"
      resource.end_date:
        type: string
        required: false
        example: "2023-10-10"
      resource.comentary:
        type: string
        required: false
        example: "PRUEBA DE COMENTARIO"
    responses:
        200:
          body:
            application/json:
              type: resource
              example: !include examples/resource/resource_id/post_200.json
  /{resource-id}:
    get:
      uriParameters:
        resource-id:
          type: number
          description: resource identifier
          # minLength: 1
          # maxLength: 10
      responses:
        200:
          body:
            application/json:
              type: resource
              example: !include examples/resource/resource_id/get_200.json
    put:
      body:
        application/json:
          properties:
          resource.name:
        type: string
        required: false
        example: "ANTONIO"
      resource.last_name:
        type: string
        required: false
        example: "ANZURES"
      resource.second_last_name:
        type: string
        required: false
        example: "MONTECILLO"
      resource.fkResourceStatus:
        type: number
        required: true
        example: 1
      resource.letters_gft:
        type: string
        required: false
        example: "JOAZ"
      resource.starting_date:
        type: string
        required: false
        example: "2019-10-10"
      resource.end_date:
        type: string
        required: false
        example: "2023-10-10"
      resource.comentary:
        type: string
        required: false
        example: "PRUEBA DE COMENTARIO"
            
      responses:
        200:
          body:
            application/json:
              example: !include examples/resource/resource_id/put_200.json
    patch:
      body:
        application/json:
          properties:
            pluskimble.address:
              type: string
              required: false
              example: "Insurgentes Sur 345, Hipódromo, 06170, CDMX"
            pluskimble.contact:
              type: number
              required: false
              example: 55674309
            pluskimble.schedule:
              type: string
              required: false
              example: "Lunes a Domingo de 9:00am a 8:00pm"
            pluskimble.logo:
              type: string
              required: false
              example: "logo.jpg"
            pluskimble.name:
              type: string
              required: false
              example: "logo.jpg"
      responses:
        200:
          body:
            application/json:
              example: !include examples/pluskimbles/pluskimble_id/patch_200.json
    delete:
      responses:
        200:
          body:
            application/json:
              example: !include examples/pluskimbles/pluskimble_id/delete_200.json
    