#%RAML 1.0
title: +kimble
description: +kimble web app
version: 0.0
baseUri: http://localhost:8081/plus-kimble/v0

uses:
  account:  types/account.raml
  cost_family:  types/cost_family.raml
  month:  types/month.raml
  non_work_day:  types/non_work_day.raml
  project:  types/project.raml
  resource_hours:  types/resource_hours.raml
  pagination: glapi-global-apis-commons-commons/types/pagination.raml

resourceTypes: 
  collection: !include glapi-global-apis-commons-commons/resourceTypes/collection.raml

traits: 
  pageable: !include glapi-global-apis-commons-commons/traits/pageable.raml

/accounts:
  description: |
    Accounts
  type: collection
  get:
    is: [pageable]
    description: |
      accounts list
    queryParameters:
      account.id:
        description: |
          Account id
        type: string
        required: true
        example: "2"
      account.account_name:
        description: |
          Account namee
        type: string
        required: true
        example: "Banco 1"
      account.fk_family:
        description: |
          Family to which the account belongs
        type: number
        required: true
        example: 1
    responses:
      200:
        body:
          application/json:
            type: account
            example: !include examples/accounts/get_200.json
  post:
    body:
      application/json:
        properties:
          account.id:
            description: |
              Account id
            type: string
            required: true
            example: "2"
          account.account_name:
            description: |
              Account name
            type: string
            required: true
            example: "Banco 1"
          account.fk_family:
            description: |
              Family to which the account belongs
            type: number
            required: true
            example: 1
    responses:
        200:
          body:
            application/json:
              type: account
              example: !include examples/accounts/post_200.json
  /{account-id}:
    get:
      uriParameters:
        account-id:
          type: string
          description: Account identifier
      responses:
        200:
          body:
            application/json:
              type: account
              example: !include examples/accounts/account_id/get_200.json
    patch:
      body:
        application/json:
          properties:
            account.id:
              type: string
              required: true
              example: "1"
            account.name:
              type: number
              required: true
              example: "Banco 1"
            account.fk_family:
              type: string
              required: true
              example: 1
      responses:
        200:
          body:
            application/json:
              example: !include examples/accounts/account_id/patch_200.json

/cost_families:
  description: |
    Cost families
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      lists all cost faamilies
    queryParameters:
      cost_family.id:
        description: |
          Cost family id
        type: number
        required: true
        example: 1
      cost_family.cost_family:
        description: |
          Cost family
        required: true
        example: "Cost family"
    responses:
      200:
        body:
          application/json:
            type: cost_family
            example: !include examples/cost_families/get_200.json
  post:
    body:
      application/json:
        properties: 
          cost_family.id:
            description: |
              Identifier of a cost family
            type: number
            required: true
            example: 1
    responses:
      200:
        body:
          application/json:
            type: cost_family
            example: !include examples/cost_families/post_200.json

  /{cost_family-id}:
    get:
      uriParameters:
        cost_family-id:
          type: integer
          description: Identifier of a cost family
      responses:
        200:
          body:
            application/json:
              type: cost_family
              example: !include examples/cost_families/cost_family_id/get_200.json

    patch:
      body:
        application/json:
          properties:
            cost_family.id:
              type: integer
              required: true
              example: 1
            cost_family.cost_family:
              type: string
              required: true
              example: "Banco 1"
      responses:
        200:
          body:
            application/json:
              example: !include examples/cost_families/cost_family_id/patch_200.json

/months:
  description: |
    Month list
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      Month list
    queryParameters:
      month.id:
        description: |
          Month id
        type: number
        required: true
        example: 1
      month.month_name:
        description: |
          Month naame
        required: true
        example: "January"
    responses:
      200:
        body:
          application/json:
            type: month
            example: !include examples/months/get_200.json
  post:
    body:
      application/json:
        properties: 
          month.id:
            description: |
              Month identifier
            type: number
            required: true
            example: 1
    responses:
      200:
        body:
          application/json:
            type: month
            example: !include examples/months/post_200.json

  /{month-id}:
    get:
      uriParameters:
        month-id:
          type: integer
          description: Month identifier
      responses:
        200:
          body:
            application/json:
              type: month
              example: !include examples/months/month_id/get_200.json
    patch:
      body:
        application/json:
          properties:
            month.id:
              type: integer
              required: true
              example: 1
            month.month_name:
              type: string
              required: true
              example: "January"
      responses:
        200:
          body:
            application/json:
              example: !include examples/months/month_id/patch_200.json

/non_work_day:
  description: |
    List of non-working days
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      List of non-working days
    queryParameters:
      non_work_day.id:
        description: |
          Non work day identifier
        type: number
        required: true
        example: 1
      non_work_day.day:
        description: |
          Non work day
        required: true
        example: 1
      non_work_day.fk_month:
        description: |
          Non-working day of the month
        required: true
        example: 1
      non_work_day.year:
        deescription: |
          Non working days of the year
    responses:
      200:
        body:
          application/json:
            type: non_work_day
            example: !include examples/months/get_200.json
  post:
    body:
      application/json:
        properties: 
          month.id:
            description: |
              Month identifier
            type: number
            required: true
            example: 1
    responses:
      200:
        body:
          application/json:
            type: non_work_day
            example: !include examples/months/post_200.json

  /{non-work-day-id}:
    get:
      uriParameters:
        non_work_day-id:
          type: integer
          description: Non work day identifier
      responses:
        200:
          body:
            application/json:
              type: month
              example: !include examples/non_work_days/non_work_day_id/get_200.json

    patch:
      body:
        application/json:
          properties:
            non_work_day.id:
              type: number
              required: true
              example: 1
            non_work_day.day:
              type: number
              required: true
              example: 1
            non_work_day.fk_month:
              type: number
              required: true
              example: 1
            non_work_day.year:
              type: number
              required: true
              example: 1
      responses:
        200:
          body:
            application/json:
              example: !include examples/non_work_day/non_work_day_id/patch_200.json

/projects:
  description: |
    List of projects
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      List of projects
    queryParameters:
      project.id:
        description: |
          List of projects
        type: number
        required: true
        example: 1
      project.project_name:
        description: |
          Project's name
        required: true
        example: 1
      project.fk_account:
        description: |
          Account related to the project
        required: true
        example: 1
      projects.fk_pm:
        deescription: |
          Project Management related to the project
          required: true
          example: 1
    responses:
      200:
        body:
          application/json:
            type: project
            example: !include examples/projects/get_200.json
  post:
    body:
      application/json:
        properties: 
          month.id:
            description: |
              Month identifier
            type: number
            required: true
            example: 1
    responses:
      200:
        body:
          application/json:
            type: non_work_day
            example: !include examples/projects/post_200.json

  /{projects-id}:
    get:
      uriParameters:
        project-id:
          type: integer
          description: Project Identifier
      responses:
        200:
          body:
            application/json:
              type: project
              example: !include examples/projects/project_id/get_200.json
    patch:
      body:
        application/json:
          properties:
            project.id:
              type: string
              required: true
              example: "KKE000001"
            project.project_name:
              type: string
              required: true
              example: "Project name"
            project.fk_account:
              type: string
              required: true
              example: "Account"
            project.fk_pm:
              type: number
              required: true
              example: 1
      responses:
        200:
          body:
            application/json:
              example: !include examples/projects/project_id/patch_200.json

/resources_hours:
  description: |
    Resource Hours
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      Resource Hours List
    queryParameters:
      resource_hours.id:
        description: |
          Resource hours identifier
        type: number
        required: true
        example: 1
      resource_hours.week:
        description: |
          Resource hours per week
        required: true
        example: 1
      resource_hours.hours:
        description: |
          Resource Hours
        required: true
        example: 1
      resource_hours.fk_state:
        deescription: |
          Relationship of the state with the hours of the resource
        required: true
        example: 1
      resource_hours.fk_month:
        deescription: |
          Relation of the month with the hours of the resource
        required: true
        example: 1
      resource_hours.fk_day:
        deescription: |
          Relationship of the day with the hours of the resource
        required: true
        example: 1
      resource_hours.fk_attemp:
        deescription: |
          Relation of the attempt with the hours of the resource
        required: true
        example: 1
      resource_hours.fk_resource:
        deescription: |
          Relation of the resource with the hours
        required: true
        example: 1
    responses:
      200:
        body:
          application/json:
            type: project
            example: !include examples/resources_hours/get_200.json
  post:
    body:
      application/json:
        properties: 
          resource_hours.id:
            description: |
              Resource hours identifier
            type: number
            required: true
            example: 1
    responses:
      200:
        body:
          application/json:
            type: resource_hours
            example: !include examples/resources_hours/post_200.json

  /{resources_hours-id}:
    get:
      uriParameters:
        resource_hours-id:
          type: integer
          description: Resource hours identifier
      responses:
        200:
          body:
            application/json:
              type: resource_hours
              example: !include examples/resources_hours/resource_hours_id/get_200.json
    patch:
      body:
        application/json:
          properties:
            resource_hours.id:
              type: number
              required: true
              example: 1
            resource_hours.week:
              type: number
              required: true
              example: 1
            resource_hours.hours:
              type: number
              required: true
              example: 8.0
            resource_hours.fk_state:
              type: number
              required: true
              example: 1
            resource_hours.fk_month:
              type: number
              required: true
              example: 1
            resource_hours.fk_attemp:
              type: number
              required: true
              example: 1
            resource_hours.fk_resource:
              type: number
              required: true
              example: 123456
      responses:
        200:
          body:
            application/json:
              example: !include examples/resources_hours/resource_hours_id/patch_200.json
