#%RAML 1.0
types:
  account:
    type: array
    description: Entity representing accounts
    properties:
      id:
        type: string
        description: Accounts Identifier
        reuquired: true
      account_name:
        type: string
        description: Accounts name
        required: true
      fk_family:
        type: integer
        description: Family to which the account belongs
        required: true