#%RAML 1.0
types:
  account:
    type: array
    description: Entity representing accounts
    properties:
      id:
        type: string
        description: Accounts Identifier
        required: false
      name:
        type: string
        description: Accounts name
        required: false
      cost_family:
        type: integer
        description: cost family to which the account belongs
        required: false