#%RAML 1.0
types:
  cost_family:
    type: array
    description: Cost family
    properties:
      id:
        type: integer
        description: Identifier of the cost families
        reuquired: true
      cost_family:
        type: string
        description: Cost families
        required: true