#%RAML 1.0
types:
  cost_family:
    type: object
    description: Cost family
    properties:
      id:
        type: integer
        description: Identifier of the cost family
        reuquired: true
      cost_family:
        type: string
        description: Cost family
        required: true