#%RAML 1.0
types:
  resource:
    type:object
    description: Entity that represent an kimble status
    properties:
      id:
        type: number
        description: identify of the status kimble
        required: true
      status_name:
        type: string
        description: identify the name of the status kimble
        required: true
      