#%RAML 1.0
types:
  kimble_status:
    type: array
    description: Entity that represent an kimble status
    properties:
      id:
        type: integer
        description: identify of the status kimble
        required: false
      status_name:
        type: string
        description: identify the name of the status kimble
        required: false