#%RAML 1.0
types:
  month:
    type: object
    description: Month of the year
    properties:
      id:
        type: integer
        description: Month identifier
        reuquired: true
      month_name:
        type: string
        description: Month name
        required: true