#%RAML 1.0
types:
  month:
    type: array
    description: Months of the year
    properties:
      id:
        type: integer
        description: Identifier of the collection of the months of the year
        required: false
      month_name:
        type: string
        description: Name of the months of the year
        required: false