#%RAML 1.0
types:
  non_work_days:
    type: array
    description: Non-work days entity
    properties:
      id:
        type: integer
        description: Non-work days identifier
        required: false
      day:
        type: integer
        description: Non-work days
        required: false
      fk_month:
        type: integer
        description: Foreign key of the months of the non-work days
        required: false
      year:
        type: integer
        description: Year to which the non-work day corresponds
        required: false
