#%RAML 1.0
types:
  resource:
    type:object
    description: Entity that represent an person
    properties:
      id:
        type: integer
        description: identify of the person
        required: true
      name:
        type: string
        description: identify the name of the person
        required: true
      last_name:
        type: string
        description: identify the last name of the person
        required: true
      second_last_name:
        type: string
        description: identify the second last name of the person
        required: true