#%RAML 1.0
types:
  project:
    type: array
    description: Project
    properties:
      id:
        type: integer
        description: Projects
        reuquired: true
      project_name:
        type: string
        description: Projects name
        required: true
      fk_account:
        type: string
        description: Accounts associated with the projects
        required: true
      fk_pm:
        type: integer
        description: Projects magements
        required: true