#%RAML 1.0
types:
  resource:
    type:object
    description: Entity that represent an resource
    properties:
      id:
        type: number
        description: identify of the relation resource project hour id
        required: false
      fk_hours_resource:
        type: string
        description: identify the foreign key of the element hours resource
        required: true
      fk_resource_project:
        type: number
        description: identify the foreign key of the relation resource proyect
        required: true
      