#%RAML 1.0
types:
  resource_status:
    type:object
    description: Entity that represent an resource_status
    properties:
      id:
        type: integer
        description: identify of the resource_status
        required: true
      name_status:
        type: string
        description: identify the name of the resource_status
        required: false