#%RAML 1.0
types:
  resource:
    type:object
    description: relation between resources and projects list
    properties:
      id:
        type: integer
        description: identify of the relation between resources and projects
        required: true
      fk_resource:
        type: string
        description: identify the id of the resource
        required: false
      fk_proyect:
        type: integer
        description: identify the id of the proyect
        required: false
      status:
        type: integer
        description: identify the status of the relation  between resources and projects
        required: false
      starting_date:
        type: string
        description: identify the admission date of  relation  between resources and projects
        required: false
      end_date:
        type: string
        description: identify the last date of the  relation  between resources and projects
        required: false
      