#%RAML 1.0
types:
  respurce_hours:
    type: array
    description: Hours imputed by active resources
    properties:
      id:
        type: integer
        description: Identifier of hours imputed by the resources
        reuquired: true
      week:
        type: integer
        description: Week corresponding to working hours
        required: true
      hours:
        type: float
        description: Hours corresponding to the week worked
        required: true
      fk_state:
        type: integer
        description: State in which the hours of resources are found
        required: true
      fk_month:
        type: integer
        description: Hours related to the month
        required: true
      working_day:
        type: integer:
        description: Hours of the day worked by the resource
        required: true
      fk_attemp:
        type: integer
        description: Set of hours imputed to the kimble by an active resource in a specific month
        required: true
      fk_resource:
        type: integer
        description: Hours imputed by a resource
        required: true